### ISSUE TITLE
[BUG] context returned is null when package being tested against channel containing of no videos

### ISSUE THREAD

**Issue by sunnypaul19999** [Hexer10/youtube_explode_dart#135]
**The Bug**
FatalFailureException is thrown when being tested against a channel containing no uploads.
I have given the original code and a fix made to the original(fix is rusty but seems to work). 

**To Reproduce**
Orignal code that was giving exception.
```dart
//snippet form class ChannelUploadPage
late final List<ChannelVideo> uploads =
      getContentContext().map(_parseContent).whereNotNull().toList();

  List<Map<String, dynamic>> getContentContext() {
    List<Map<String, dynamic>>? context;
    if (root.containsKey('contents')) {
      context = root
          .get('contents')
          ?.get('twoColumnBrowseResultsRenderer')
          ?.getList('tabs')
          ?.map((e) => e['tabRenderer'])
          .cast<Map<String, dynamic>>()
          .firstWhereOrNull((e) => e['selected'] as bool)
          ?.get('content')
          ?.get('sectionListRenderer')
          ?.getList('contents')
          ?.firstOrNull
          ?.get('itemSectionRenderer')
          ?.getList('contents')
          ?.firstOrNull
          ?.get('gridRenderer')
          ?.getList('items')
          ?.cast<Map<String, dynamic>>();
    }
    if (context == null && root.containsKey('onResponseReceivedActions')) {
      context = root
          .getList('onResponseReceivedActions')
          ?.firstOrNull
          ?.get('appendContinuationItemsAction')
          ?.getList('continuationItems')
          ?.cast<Map<String, dynamic>>();
    }
    if (context == null) {
      //return List<Map<String, dynamic>>.empty();
      throw FatalFailureException('Failed to get initial data context.');
    }
    return context;
  }
```

**Stacktrace**
Unhandled exception:
FatalFailureException: Failed to get initial data context.
#0      _InitialData.getContentContext (package:youtube_explode_dart/src/reverse_engineering/responses/channel_upload_page.dart:130:7)
#1      _InitialData.uploads (package:youtube_explode_dart/src/reverse_engineering/responses/channel_upload_page.dart:97:7)
#2      _InitialData.uploads (package:youtube_explode_dart/src/reverse_engineering/responses/channel_upload_page.dart)     
#3      ChannelClient.getUploadsFromPage (package:youtube_explode_dart/src/channels/channel_client.dart:127:26)

**Fix made to above orginal code that was giving exception to channels of no uploads.
Below code contains chages that I have made to the above orginal code to suit channels that has no uploads.**
```dart
//checking if context returned is an empty list
//so if channel has no video uploads shall return an empty list of type List<ChannelVideo>
late final List<ChannelVideo> uploads = (getContentContext().isEmpty)
      ? List<ChannelVideo>.empty()
      : getContentContext().map(_parseContent).whereNotNull().toList();

  List<Map<String, dynamic>> getContentContext() {
    List<Map<String, dynamic>>? context;
    if (root.containsKey('contents')) {
      context = root
          .get('contents')
          ?.get('twoColumnBrowseResultsRenderer')
          ?.getList('tabs')
          ?.map((e) => e['tabRenderer'])
          .cast<Map<String, dynamic>>()
          .firstWhereOrNull((e) => e['selected'] as bool)
          ?.get('content')
          ?.get('sectionListRenderer')
          ?.getList('contents')
          ?.firstOrNull
          ?.get('itemSectionRenderer')
          ?.getList('contents')
          ?.firstOrNull
          ?.get('gridRenderer')
          ?.getList('items')
          ?.cast<Map<String, dynamic>>();
    }
    if (context == null && root.containsKey('onResponseReceivedActions')) {
      context = root
          .getList('onResponseReceivedActions')
          ?.firstOrNull
          ?.get('appendContinuationItemsAction')
          ?.getList('continuationItems')
          ?.cast<Map<String, dynamic>>();
    }
    if (context == null) {
      return List<Map<String, dynamic>>.empty();//returning an empty list instead of throwing an exception
      //I have commented out the below exception
      //throw FatalFailureException('Failed to get initial data context.');
    }
    return context;
  }
```
** These changes that I have made to code seems to work and I am testing it but if you looked into this and tested it out would be helpful**

**Comment by Hexer10** [comment]
I've just released a new version v`1.9.7` which should fix this issue. Please reopen the issue if this still happens.
