### ISSUE TITLE
[BUG] SearchList.nextPage() not working?

### ISSUE THREAD

**Issue by alexgaya** [Hexer10/youtube_explode_dart#158]
**Describe the bug**
Hi, first of all, awesome work!

I have a problem with the method nextPage(), it's returning an Unhandled Exception: Null check operator used on a null value.

I'm new to Flutter so the chances of me being wrong are high.

**To Reproduce**
Include the code which doesn't work in the code markdown..
```dart
    var nextVideos = await _videos?.nextPage() ?? null;
    if (nextVideos != null) {
      _videos!.addAll(nextVideos);
      notifyListeners();
    }
```

**Stacktrace**
E/flutter (12505): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter (12505): #0      IOClient.send (package:http/src/io_client.dart:30:36)
E/flutter (12505): #1      YoutubeHttpClient.send (package:youtube_explode_dart/src/reverse_engineering/youtube_http_client.dart:200:24)
E/flutter (12505): #2      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:38)
E/flutter (12505): #3      BaseClient.post (package:http/src/base_client.dart:32:7)
E/flutter (12505): #4      YoutubeHttpClient.post (package:youtube_explode_dart/src/reverse_engineering/youtube_http_client.dart:88:21)
E/flutter (12505): #5      YoutubeHttpClient.sendPost.<anonymous closure> (package:youtube_explode_dart/src/reverse_engineering/youtube_http_client.dart:183:25)
E/flutter (12505): #6      YoutubeHttpClient.sendPost.<anonymous closure> (package:youtube_explode_dart/src/reverse_engineering/youtube_http_client.dart:182:27)
E/flutter (12505): #7      retry (package:youtube_explode_dart/src/retry.dart:17:28)
E/flutter (12505): #8      YoutubeHttpClient.sendPost (package:youtube_explode_dart/src/reverse_engineering/youtube_http_client.dart:182:12)
E/flutter (12505): #9      SearchPage.nextPage (package:youtube_explode_dart/src/reverse_engineering/pages/search_page.dart:32:26)
E/flutter (12505): #10     SearchList.nextPage (package:youtube_explode_dart/src/search/search_list.dart:22:30)
E/flutter (12505): #11     YtProvider.fetchMoreVideos (package:downloader/providers/yt_provider.dart:69:37)

**Enviroment: (please complete the following information):**
 - Enviroment: [Flutter]
 - Version [2.2.3 channel stable]
 - YoutubeExplode Version [^1.10.4]

**Comment by sunnypaul19999** [comment]
is "_videos" initialized? if you could show the initialization part would be good

**Comment by Hexer10** [comment]
I'm closing this due to inactivity if you still need help please reopen with the information that was requested.
