### ISSUE TITLE
Null check operator used on a null value only for specific research

### ISSUE THREAD

**Issue by poka-IT** [Hexer10/youtube_explode_dart#184]
Something I can't explain, everything work fine except for this research:

`yt.search.getVideos('Sudan Archives');`

Please try it and tell me if you got the same error from this package with this termes of research ?
I don't know what is specific to this research...

```
Unhandled exception:
Null check operator used on a null value
#0      _InitialData._parseContent (package:youtube_explode_dart/src/reverse_engineering/pages/search_page.dart:213:37)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#3      IterableNullableExtension.whereNotNull (package:collection/src/iterable_extensions.dart:563:25)
#4      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:182:26)
#5      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
#6      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#7      new List.of (dart:core-patch/array_patch.dart:51:28)
#8      Iterable.toList (dart:core/iterable.dart:388:12)
#9      _InitialData.searchContent (package:youtube_explode_dart/src/reverse_engineering/pages/search_page.dart:124:62)
#10     _InitialData.searchContent (package:youtube_explode_dart/src/reverse_engineering/pages/search_page.dart)
#11     SearchPage.searchContent (package:youtube_explode_dart/src/reverse_engineering/pages/search_page.dart:21:66)
#12     SearchPage.searchContent (package:youtube_explode_dart/src/reverse_engineering/pages/search_page.dart)
#13     SearchClient.getVideos (package:youtube_explode_dart/src/search/search_client.dart:29:14)
```

**Comment by Hexer10** [comment]
I've just released a fix in `1.10.9+1`. This was happening since the channel named `Sudan Archives` didn't provide a "video count" field while the youtube client was expecting one. Now if no video count is present, it will default to `-1`.
