### ISSUE TITLE
NoSuchMethodError: The method 'split' was called on null.

### ISSUE THREAD

**Issue by lilboat72** [Hexer10/youtube_explode_dart#24]
Tried calling `singles('https://www.youtube.com/watch?v=RIuk23XHYj0')` but received error:

 `Unhandled exception:
NoSuchMethodError: The method 'split' was called on null.
Receiver: null
Tried calling: split("&")
`

**Singles Function**
```
Future singles(String myId) async{
  // Intializing
  String id = YoutubeExplode.parseVideoId(myId);
  print('ID: --------------- $id');
  if(id == null){
    return '$id is null';
  }
  var yt = YoutubeExplode();
  var metadata = await yt.getVideo(id); // Returns a Video instance.
  print('METADATA: -------------- $metadata');

  MediaStreamInfoSet mediaStreams = await yt.getVideoMediaStream(id); // Actual downloading here
  var audio = mediaStreams.audio;
  print(audio);

  yt.close();
}
```

**Full stacktrace**

```
youtube_download.dart: Warning: Interpreting this as package URI, 'package:test_download/youtube_download.dart'.
ID: --------------- RIuk23XHYj0
METADATA: -------------- Video(RIuk23XHYj0): JACKBOYS - GANG GANG feat. Sheck Wes, Don Toliver, Luxury Tax 50 & Cactus Jack (Official)
Unhandled exception:
NoSuchMethodError: The method 'split' was called on null.
Receiver: null
Tried calling: split("&")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Uri.splitQueryString (dart:core/uri.dart:1180:18)
#2      decipherUrl (package:youtube_explode_dart/src/cipher/cipher.dart:100:23)
#3      YoutubeExplode.getVideoMediaStream (package:youtube_explode_dart/src/youtube_explode_base.dart:62:23)
<asynchronous suspension>
#4      singles (package:test_download/youtube_download.dart:14:46)
<asynchronous suspension>
#5      main (package:test_download/youtube_download.dart:43:3)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by Hexer10** [comment]
Fixed with #23 open a new issue if this still persist.
