### ISSUE TITLE
[BUG] VideoUnavailableException when video is available on youtube

### ISSUE THREAD

**Issue by MxD-js** [Hexer10/youtube_explode_dart#271]
**Describe the bug**
YoutubeExplode library throws a VideoUnavailableException but when I go to youtube.com the video is available and has multiple streams. 1080, 720, 360 and so on. This usually happens when a stream was live and then the live stream ended and video is available on youtube after the live stream. If I wait long enough, or the following day the issue resolves it self, but this can be reproduced everytime a stream transitions from live to not live. 

![image](https://github.com/Hexer10/youtube_explode_dart/assets/60336163/6a762621-4c54-4bd9-a7da-d2f2b2479b11)

**To Reproduce**
Try to stream a live video then end the stream and attempt to play back the video after it's posted to youtube channel.
```dart
Future<Uri> _getYTMetadata(
    String videoId, YoutubeExplode ytXplode, bool isLive) async {
  if (isLive) {
    final liveStreamUrl =
        await ytXplode.videos.streams.getHttpLiveStreamUrl(VideoId(videoId));
    return Uri.parse(liveStreamUrl);
  } else {
    try {
      var manifest = await ytXplode.videos.streamsClient.getManifest(videoId);
      var muxedInfo = manifest.muxed.bestQuality;
      var videoUri = muxedInfo.url;
      return videoUri;
    } catch (e, stack) {
      print(e);
      print(stack);

      throw e;
    }
    // var streamInfo = manifest.video.withHighestBitrate();
  }
}
```

Youtube screenshot showing the video is available
![image](https://github.com/Hexer10/youtube_explode_dart/assets/60336163/436e676c-6562-47fe-85d6-49395d6279f5)

**Stacktrace**
I/flutter ( 5847): VideoUnavailableException: Video "n39W2uq4aXw" does not contain any playable streams.
I/flutter ( 5847): #0      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:178:9)
I/flutter ( 5847): <asynchronous suspension>
I/flutter ( 5847): #1      retry (package:youtube_explode_dart/src/retry.dart:16:14)
I/flutter ( 5847): <asynchronous suspension>
I/flutter ( 5847): #2      _getYTMetadata (package:scc_mobile_app_v2/src/features/video_player/presentation/video_player_item_controller.dart:66:22)
I/flutter ( 5847): <asynchronous suspension>
I/flutter ( 5847): #3      videoPlayerItemController (package:scc_mobile_app_v2/src/features/video_player/presentation/video_player_item_controller.dart:23:15)
I/flutter ( 5847): <asynchronous suspension>
I/flutter ( 5847): #4      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348:9)
I/flutter ( 5847): <asynchronous suspension>

**Enviroment: (please complete the following information):**
 - Enviroment: [Flutter o Dart VM]
 - Version 3.16.9
 - YoutubeExplode Version :2.1.0
**Additional context**

Flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.3 23D56 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
[✓] VS Code (version 1.86.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**Comment by Hexer10** [comment]
Hi, sorry for the late reply, do  you still get this error? I've just tried with the video id you provided any I could get all the streams correctly.
