### ISSUE TITLE
[BUG] Can't retreive comment of any video

### ISSUE THREAD

**Issue by bazini** [Hexer10/youtube_explode_dart#276]
**Fetching comments**
I can not retrieve comments from any video. I got always this error.

**Error output**
```E/flutter ( 8895): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 8895): #0      _Comment._commentRenderer (package:youtube_explode_dart/src/reverse_engineering/clients/comments_client.dart:141:26)
E/flutter ( 8895): #1      _Comment._commentRenderer (package:youtube_explode_dart/src/reverse_engineering/clients/comments_client.dart)
E/flutter ( 8895): #2      _Comment.author (package:youtube_explode_dart/src/reverse_engineering/clients/comments_client.dart:158:7)
E/flutter ( 8895): #3      _Comment.author (package:youtube_explode_dart/src/reverse_engineering/clients/comments_client.dart)
E/flutter ( 8895): #4      CommentsClient.getComments.<anonymous closure> (package:youtube_explode_dart/src/videos/comments/comments_client.dart:32:17)
E/flutter ( 8895): #5      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
E/flutter ( 8895): #6      ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
E/flutter ( 8895): #7      new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:162:27)
E/flutter ( 8895): #8      new _List.of (dart:core-patch/array.dart:127:20)
E/flutter ( 8895): #9      new List.of (dart:core-patch/array_patch.dart:39:50)
E/flutter ( 8895): #10     ListIterable.toList (dart:_internal/iterable.dart:224:7)
E/flutter ( 8895): #11     CommentsClient.getComments (package:youtube_explode_dart/src/videos/comments/comments_client.dart:42:12)
E/flutter ( 8895): <asynchronous suspension>
E/flutter ( 8895): #12     _VideoComment._getComments (package:anat/inc/video_comment.dart:37:32)
E/flutter ( 8895): <asynchronous suspension>
E/flutter ( 8895): 
```

**Enviroment: (please complete the following information):**
 - Enviroment: [Flutter o Dart VM]
 - Flutter Version 3.19.5
 - Dart 3.3.3 
 - YoutubeExplode 2.2.0

**Comment by Foxify52** [comment]
This was taken from the getComments() function

"Returns a [List] containing the first batch of comments or null if the video has comments disabled. You can use [CommentsList.nextPage()] to get the next batch of comments.

WARNING: As of v2.2.0 this is broken due to yt updates."
