### ISSUE TITLE
[BUG] Unhandled Exception: FatalFailureException: Failed to perform an HTTP request to YouTube due to a fatal failure.

### ISSUE THREAD

**Issue by wandiaprianto93** [Hexer10/youtube_explode_dart#284]
**Describe the bug**
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FatalFailureException: Failed to perform an HTTP request to YouTube due to a fatal failure.
E/flutter (20848): In most cases, this error indicates that YouTube most likely changed something, which broke the library.
E/flutter (20848): If this issue persists, please report it on the project's GitHub page.
E/flutter (20848): Request: get https://rr1---sn-uigxxi0ujipnvo-2o3l.googlevideo.com/videoplayback?expire=1726743252&ei=dK7rZsC0BoLx4-EPoZ-S4QQ&ip=114.10.137.247&id=o-AGUm60Mfj1wtGqsYRp2Z1d57mX9Ve4BI3mcotl7J9oe8&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=zm&mm=31%2C29&mn=sn-uigxxi0ujipnvo-2o3l%2Csn-npoldn7y&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=355000&bui=AXLXGFSn6nGHoWO-xdMKt3fjJy9y12-2HvFeftmFxfZxJzVoSMcwr524_enPzTOM2yExz-z4pi7n-V2k&spc=54MbxU3rCaIJy_-RcvMiTngO5qEMUb6eqhU8rbxboElxP1bChOLNexfSDqssK64&vprv=1&svpuc=1&mime=video%2Fmp4&ns=gT7WHVHcFgSp7Er3mpB2AXoQ&rqh=1&gir=yes&clen=6062931&ratebypass=yes&dur=93.831&lmt=1725074230158045&mt=1726721112&fvip=4&c=WEB&sefc=1&txp=6209224&n=VweI5EXlov-MiSG1&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABPmVW0wRAIgXbjgh-8XEC-5Xk4N6kPBev80d-ugHWUZ-vyDBJtGmZUCICXBHLQBGzbcKsrcZBF65XLbboABv8A5NoiLktfAjKNl&sig=AJfQdSswRQIhAIg1qa_3-JVY8YQSmqlGhjF-wN7Q3naG4LLyJuIZRPS0AiAGa62R3VCvdzZzwSrChe97408eBVFt1cjmNbJn2VpcVA%3D%3D&range=0-6062930
E/flutter (20848): Response: (403)
E/flutter (20848): 
E/flutter (20848): #0      YoutubeHttpClient._validateResponse (package:youtube_explode_dart/src/reverse_engineering/youtube_http_client.dart:59:7)
E/flutter (20848): #1      YoutubeHttpClient._getStream (package:youtube_explode_dart/src/reverse_engineering/youtube_http_client.dart:185:11)
E/flutter (20848): <asynchronous suspension>
E/flutter (20848): #2      _StreamController._add (dart:async/stream_controller.dart:656:3)
E/flutter (20848): <asynchronous suspension>

**To Reproduce**
Include the code which doesn't work in the code markdown..
```dart
// You can provide either a video ID or URL as String or an instance of `VideoId`.
var videoId;
// var containerName;
await controller.yt.videos.get(link).then((value) async {
  videoId = value.id;

  // containerName = value.title;
  var streamManifest = await controller.yt.videos.streamsClient
      .getManifest(value.id);

  // videoData.

  // Get highest quality muxed stream
  var streamInfo = streamManifest.muxed.withHighestBitrate();

  // ignore: unnecessary_null_comparison
  if (streamInfo != null) {
    // Get the actual stream
    // var stream = yt.video.streamClient.get(streamInfo);
    var stream = controller.yt.videos.streamsClient.get(streamInfo);

    // if (status.isGranted) {
    // Build the directory.
    var dir = await DownloadsPathProvider.downloadsDirectory;
    var filePath = path.join(
        dir!.uri.toFilePath(), videoId.toString() + ".mp4");

    // Open the file to write.
    var file = File(filePath);
    var fileStream = file.openWrite();

    var len = streamInfo.size.totalBytes;
    var count = 0;

    pd.show(max: 100, msg: 'File Downloading...');

    // Listen for data received.
    //  var progressBar = ProgressBar();
    await for (final data in stream) {
      // Keep track of the current downloaded data.
      count += data.length;

      // Calculate the current progress.
      var progress = ((count / len) * 100).ceil();
      pd.update(value: progress);
      // print(progress);

      // Update the progressbar.
      // progressBar.update(progress);

      // Write to file.
      fileStream.add(data);
    }
    // // Pipe all the content of the stream into the file.
    // await stream.pipe(fileStream);

    await fileStream.flush();
    await fileStream.close();

    // // Close the file.
    // await fileStream.flush();
    // await fileStream.close();

    CommonWidget.toast('Video telah selesai diunduh.');
  }
}); // Returns a Video instance.
```

**Stacktrace**
Include here the stacktrace (if applicable). 

**Enviroment: (please complete the following information):**
Flutter 3.19.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 300451adae (6 months ago) • 2024-03-27 21:54:07 -0500
Engine • revision e76c956498
Tools • Dart 3.3.3 • DevTools 2.31.1

**Comment by Joseph-Nathan** [comment]
did you found any solution ?

**Comment by Hexer10** [comment]
Closed in favour of #286
